image: node:10

deploy_production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - npm install -g firebase-tools
    - cd /builds/kvasbo/tellulf-client
    - yarn install --non-interactive --pure-lockfile
    - CI=false yarn run build
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - /builds/kvasbo/tellulf-client/build/