image: node:10

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

deploy_production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    # - npm install -g firebase-tools
    - yarn add firebase-tools
    - cd /builds/kvasbo/tellulf-client
    - yarn install --non-interactive --pure-lockfile
    - CI=false yarn run build
    - cd /builds/kvasbo/tellulf-client/functions
    - yarn install --non-interactive --pure-lockfile
    - cd /builds/kvasbo/tellulf-client
    - /node_modules/firebase_tools/node_modules/firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - /builds/kvasbo/tellulf-client/build/